### PR TITLE
Rewrite reports for mysql

### PR DESCRIPTION
**Pull request by britaumich**
I rewrote all reports to work with MySQL. 
I would like to ask you to test them on your computer because I believe (I hope) you have the real data in your database.
I have almost nothing in the database and therefore can't test the queries.

### CODE REVIEW

**Review by rsmoke — CHANGES_REQUESTED** [review]
make dates dynamic to match the current active camp year

**Comment by britaumich** [comment]
I replaced the hardcoded camp year with a variable. Please check it again.

**Comment by britaumich** [comment]
Please check it again - last time, I hope.

**Review by rsmoke — APPROVED** [review]
Looks good

**Pull request merged**
