### PR TITLE
Fix_activeadmin_error

### PR DESCRIPTION
**Pull request by rsmoke**
This PR addresses the update of gem activeadmin. It wraps teh filters that were preloading in a Proc so they are called until they are needed.
I also added ransack associations and attributes to close a security hole.
I also updated the seed file so you can reset your database as needed

### CODE REVIEW

**Comment by britaumich** [comment]
@rsmoke in Active Admin I tried to add a taxform file in a Financial Aid request and got an error in the log:

`app/models/financial_aid.rb:36:in `acceptable_taxform'
10:14:16 web.1     |   TRANSACTION (0.1ms)  ROLLBACK`

On the page, nothing happened, no errors, no redirection to a show page. 
In the Application, I can upload all files, and it works fine.
I can't figure out what the error is. 

It is unrelated to the Active Admin changes because the same problem exists in my branch where Active Admin is not updated.
How do you want to proceed? I can approve this pull request because I see that Active Admin works now, and the taxform upload error will be addressed separately. Or do you want to fix the error here?

**Comment by rsmoke** [comment]
@britaumich I ran through the creation of a user application and was able to add a financial aid request in both the user side and the admin side on my local setup.

Go ahead and approve the PR and I will watch for errant behavior with respect to finaid activity

**Comment by britaumich** [comment]
I will approve the pull request around 2:45 pm. Did you try to upload a tax form from Active Admin to a financial aid request that has no tax form - updating the record? It does work for me to update the tax form file, but I got the error when l uploaded a file to a record that had no tax form.Sent from my iPhoneOn Jan 8, 2024, at 12:06 PM, rsmokeUM ***@***.***> wrote:﻿
@britaumich I ran through the creation of a user application and was able to add a financial aid request in both the user side and the admin side on my local setup.
Go ahead and approve the PR and I will watch for errant behavior with respect to finaid activity

**Comment by rsmoke** [comment]
> I will approve the pull request around 2:45 pm. Did you try to upload a tax form from Active Admin to a financial aid request that has no tax form - updating the record? It does work for me to update the tax form file, but I got the error when l uploaded a file to a record that had no tax form.Sent from my iPhoneOn Jan 8, 2024, at 12:06 PM,

@britaumich I did it the way you described and it worked

**Review by britaumich — APPROVED** [review]

**Pull request merged**
