### PR TITLE
Lra 427 mmss prevent user to create multiple applications

### PR DESCRIPTION
**Pull request by britaumich**
There are so many files changed because I deleted many unneeded files from the spec directory. (That had to be done in the write-tests branch months ago, but unfortunately, no one reviewed and merged it ...)

I added validation to the ApplicationDetail and Enrollment models to check that only one record is created for every user. In case of enrollments - one record per user per campyear.

There are tests in the spec/system directory, and applicant_detail_spec.rb and enrollment_spec.rb in spec/models directory.

System tests might require updating a chromedriver to match the localhost Chrome's version. The chromedriver can be downloaded from here https://chromedriver.chromium.org/downloads. Run "which chromedriver" to find a directory where to put a new chromedriver.

### CODE REVIEW

**Review by rsmoke — COMMENTED** [review]
I love the tests and the simplicity iof the fix. I did need to run
```
$ gem update --system
$ bundle update --bundler
```
and now my mysql2 won't load. I'll boink on it with a toy hammer 🔨 
Before i could get it to run. Hmmphh

**Comment by britaumich** [comment]
I never run gem or system update with  --system

**Comment by rsmoke** [comment]
As soon as I can get this to run I will complete the PR

**Comment by britaumich** [comment]
I'll close this pull request since it does not satisfy the guide that you posted in slack and redo it.
Anyway, you have no time to review it now.

**Pull request closed without merging**
